# Generated by Django 3.0.2 on 2020-10-31 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesModel',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('contactno', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('student_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.DepartmentModel')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyModel',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('contactno', models.IntegerField(unique=True)),
                ('faculty_courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.CoursesModel')),
            ],
        ),
        migrations.AddField(
            model_name='coursesmodel',
            name='course_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.DepartmentModel'),
        ),
    ]
